name: open_system_folder_android
description: Android implementation of the open_system_folder plugin
version: 0.1.1
repository: https://github.com/olekeke999/open_system_folder
issue_tracker: https://github.com/olekeke999/open_system_folder/issues

environment:
  sdk: ^3.0.0
  flutter: '>=3.0.0'

flutter:
  plugin:
    implements: open_system_folder
    platforms:
      android:
        package: ole.keke
        pluginClass: OpenSystemFolderPlugin
        dartPluginClass: OpenSystemFolderAndroid

dependencies:
  flutter:
    sdk: flutter
  open_system_folder_platform_interface: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^6.0.0
