name: open_system_folder_platform_interface
description: A common platform interface for the open_system_folder plugin.
version: 0.1.1
repository: https://github.com/olekeke999/open_system_folder
issue_tracker: https://github.com/olekeke999/open_system_folder/issues

environment:
  sdk: ^3.0.0
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
