name: open_system_folder_ios
description: iOS implementation of the open_system_folder plugin
version: 0.1.2
repository: https://github.com/olekeke999/open_system_folder/tree/main/open_system_folder_ios
issue_tracker: https://github.com/olekeke999/open_system_folder/issues

environment:
  sdk: ^3.0.0
  flutter: '>=3.0.0'

flutter:
  plugin:
    implements: open_system_folder
    platforms:
      ios:
        pluginClass: OpenSystemFolderPlugin
        dartPluginClass: OpenSystemFolderIOS

dependencies:
  flutter:
    sdk: flutter
  open_system_folder_platform_interface: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^6.0.0
